// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70Ji6_Ctt0KAULaECt6e7Lm9tfIa436A',
    appId: '1:200391244067:web:6162e454e0adae26b5b496',
    messagingSenderId: '200391244067',
    projectId: 'changeimage-bbdc4',
    authDomain: 'changeimage-bbdc4.firebaseapp.com',
    storageBucket: 'changeimage-bbdc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfexcjrNERDwX54VD2A1D6wWaZcBVifw',
    appId: '1:200391244067:android:939d44485a4a1338b5b496',
    messagingSenderId: '200391244067',
    projectId: 'changeimage-bbdc4',
    storageBucket: 'changeimage-bbdc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflUxRtXiOZewJShR_F9GJJDQbg_M3pp0',
    appId: '1:200391244067:ios:b14ff3e5a17bfd6bb5b496',
    messagingSenderId: '200391244067',
    projectId: 'changeimage-bbdc4',
    storageBucket: 'changeimage-bbdc4.appspot.com',
    iosBundleId: 'com.example.changeImageProfile',
  );

}